### ISSUE TITLE
iOSMac support

### ISSUE THREAD

**Issue by michaeleisel** [tpoechtrager/apple-libtapi#12]
Hi, I'm trying to figure out the new tapi changes so that I can support iOSMac for project zld. In practice, I'm seeing "zippered" get resolved to UINT_MAX, rather than the 10 I see in the enum in this repo. How was the number 10 arrived at?

**Comment by tpoechtrager** [comment]
Yeah, it's probably not correct. I will have to update the TAPI library. I noticed Apple have added the TAPI sources to their LLVM repo. I didn't know that until now...

https://github.com/apple/llvm-project/tree/apple/master/llvm/lib/TextAPI

**Comment by michaeleisel** [comment]
are you sure it's all the sources in there? for example, i can't find `getPlatformSet`, and i'm not sure how to infer the value used for zippered from the source. not to mention, a lack of headers

**Comment by tpoechtrager** [comment]
No, I am not. So it's only meant for use within LLVM like LLD. 

>  I'm seeing "zippered" get resolved to UINT_MAX, rather than the 10 I see in the enum in this repo.

Where do you get this? I need a reproducible context.

**Comment by michaeleisel** [comment]
if you run a catalyst build with a breakpoint in the linker, you can dig around and see it

**Comment by tpoechtrager** [comment]
I wanted a full reproducible example. I do not even know how to compile for Catalyst. Is it `-target x86_64-apple-ios-macabi`? What SDK do I need? The macOS one?

**Comment by michaeleisel** [comment]
If you create a new xcode project as per https://developer.apple.com/documentation/uikit/mac_catalyst?language=objc and everything will be set up for you

**Comment by michaeleisel** [comment]
i don't want to take the time to do a walkthrough on how to find it, since i am confident in my own analysis, but if you compile zld yourself you can poke around

**Comment by tpoechtrager** [comment]
I am not on macOS therefore I can't use Xcode.

**Comment by michaeleisel** [comment]
🚀

**Comment by tpoechtrager** [comment]
Either provide the info I need or close the issue. I am not going to play a
game.

Michael Eisel <notifications@github.com> schrieb am Mi., 17. Juni 2020,
23:00:
