### ISSUE TITLE
tbd version 4 is not supported

### ISSUE THREAD

**Issue by glandium** [tpoechtrager/apple-libtapi#13]
Trying to use the SDK from Xcode 12 beta, I'm getting:
```
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/tmp/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
```

It turns out this tbd is using a new version, and the content starts with:
```
--- !tapi-tbd
tbd-version:     4
```

I haven't checked further what the differences might be with tapi-tbd-v3.

**Comment by tpoechtrager** [comment]
We have to wait for the next TAPI open source release. I can't do much for now.

**Comment by glandium** [comment]
It seems Xcode 11 supports tbd v4, so in theory, libtapi from https://opensource.apple.com/release/developer-tools-1131.html would work... except it's a 404 at the moment. I sent an email to opensource@apple.com.

**Comment by tonistiigi** [comment]
@tpoechtrager Upstream llvm now seems to have some support for v4 https://github.com/llvm/llvm-project/commit/28fefcc83c52291fef817afbe469b4fd0a80ca20#diff-8ab01132fc662bd764d30e0e4ad3ea3b . Not entirely sure if this is enough to move this issue forward.

**Comment by isuruf** [comment]
tapi-1100.0.11 is available now at https://opensource.apple.com/source/tapi/

**Comment by tpoechtrager** [comment]
Thanks for letting me know!

**Comment by tpoechtrager** [comment]
Updated TAPI to latest version. TBD v4 is supported now.
