### ISSUE TITLE
Build error on latest master

### ISSUE THREAD

**Issue by isuruf** [tpoechtrager/apple-libtapi#14]
```
$SRC_DIR/src/llvm/projects/libtapi/lib/Core/APIJSONSerializer.cpp:1202:10: error: could not convert 'result' from 'tapi::internal::API' to 'llvm::Expected<tapi::internal::API>'    return result;
```

I'm getting the above error on Linux x86_64.

**Comment by isuruf** [comment]
Switching from gcc 7.5 to 8.4 fixed the error

**Comment by tpoechtrager** [comment]
I have updated the requirements. Thanks for letting me know of this issue.

I don't want to take apart LLVM just to make the library compile with GCC<=7 (which is not even supported by GNU anymore). :-) The main compiler should be Clang anyway. I was able to build the library with Clang 3.9.1 so it can be still built on very old systems.
