### ISSUE TITLE
TAPI 1300.0.6.5 is available

### ISSUE THREAD

**Issue by dpogue** [tpoechtrager/apple-libtapi#24]
This is still not the most recent code, but Apple did publish the version of TAPI that shipped with Xcode 13.0 back in September 2021: https://github.com/apple-oss-distributions/tapi/tree/tapi-1300.0.6.5

**Comment by fanquake** [comment]
@dpogue note that there is a branch available now: https://github.com/tpoechtrager/apple-libtapi/tree/1300.6.5.
