### ISSUE TITLE
master branch deleted?

### ISSUE THREAD

**Issue by Ecordonnier** [tpoechtrager/apple-libtapi#29]
Hello,
was the master branch deleted on purpose, or was it a mistake?
We are integrating apple-libtapi via its branch-name, and I thus noticed that the branch had been deleted recently, because our build broke.

**Comment by tpoechtrager** [comment]
Yes, it was done on purpose. Sorry for the inconvinience this caused. I changed the branch scheme to version specific branches. That way there are no unintended upgrades.

**Comment by Ecordonnier** [comment]
OK, thanks for the fast feedback (our build-system, yocto, also references the commit hash used, so we don't get unintended upgrades regardless of the branch-name).
