### ISSUE TITLE
getting error on osxcross after latest update

### ISSUE THREAD

**Issue by felipemadero** [tpoechtrager/apple-libtapi#30]
-- TAPI version: 1300.6.5
-- Supported Architectures: i386;x86_64;x86_64h;armv4t;armv6;armv5;armv7;armv7s;armv7k;armv6m;armv7m;armv7em;arm64;arm64e
-- Performing Test SDK_SUPPORTS_I386
-- Performing Test SDK_SUPPORTS_I386 - Failed
CMake Error at .../osxcross/build/apple-libtapi/src/tapi/tools/tapi-run/CMakeLists.txt:7 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "tapi-run".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.
  The uses of the keyword signature are here:
   * cmake/modules/AddLLVM.cmake:917 (target_link_libraries)

**Comment by tpoechtrager** [comment]
What's the build command

**Comment by felipemadero** [comment]
sudo apt-get -y install clang llvm-dev libxml2-dev uuid-dev libssl-dev bash patch make tar xz-utils bzip2 gzip sed cpio libbz2-dev
cd osxcross
wget https://github.com/joseluisq/macosx-sdks/releases/download/12.3/$MACOS_SDK_FNAME -O tarballs/$MACOS_SDK_FNAME
UNATTENDED=1 ./build.sh

MACOS_SDK_FNAME=MacOSX12.3.sdk.tar.xz

**Comment by tpoechtrager** [comment]
I can't reproduce the issue on Arch Linux.

Try

    diff --git a/src/tapi/tools/tapi-run/CMakeLists.txt b/src/tapi/tools/tapi-run/CMakeLists.txt
    index b30131abf..94231f22a 100644
    --- a/src/tapi/tools/tapi-run/CMakeLists.txt
    +++ b/src/tapi/tools/tapi-run/CMakeLists.txt
    @@ -4,7 +4,7 @@ add_tapi_executable(tapi-run
       tapi-run.cpp
       )
    
    -target_link_libraries(tapi-run
    +target_link_libraries(tapi-run PRIVATE
       tapiCore
       libtapi
       )
       
What's your OS and cmake version?

**Comment by felipemadero** [comment]
it is a github runner image, ubuntu-20.04-32 , CMake 3.27.4

**Comment by felipemadero** [comment]
could you provide a tag for 1.4 so we can checkout that one while this is fixed?

**Comment by tpoechtrager** [comment]
You could help me fixing it by testing the proposed fix. I can't test it. I
have no Ubuntu installation available at the moment.

**Comment by felipemadero** [comment]
ofc

**Comment by felipemadero** [comment]
where is the fix

**Comment by tpoechtrager** [comment]
https://github.com/tpoechtrager/apple-libtapi/issues/30#issuecomment-1726445709

**Comment by felipemadero** [comment]
ok it is working.

**Comment by felipemadero** [comment]
Using:
https://github.com/felipemadero/osxcross/tree/fix
https://github.com/felipemadero/apple-libtapi/tree/fix

**Comment by felipemadero** [comment]
do you want a PR?
