### ISSUE TITLE
Add support for tapi v3 to master

### ISSUE THREAD

**Issue by kabiroberai** [tpoechtrager/apple-libtapi#9]
The iOS 11.4 and 12.0 SDKs use v3 of the tapi format, which this repository does not seem to support. Could you please add support for v3 so that these SDK versions can be used?

**Comment by kabiroberai** [comment]
Just noticed that the 2.0.0 branch has v3 support. It would be great if this branch could be merged into master since all new SDKs now use v3 🙂

**Comment by tpoechtrager** [comment]
It's too early. See here why: https://github.com/tpoechtrager/osxcross/issues/103

**Comment by kabiroberai** [comment]
I see; I just tested 2.0.0 out on Linux and I got a segfault as well. Let's hope Apple releases 2.0.0 soon

**Comment by lilili87222** [comment]
I get segment fault error on linux
